# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 01:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Professor', '0001_initial'),
        ('EducationalYear', '0001_initial'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(max_length=4000)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='Course.Course')),
                ('educational_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='EducationalYear.EducationalYear')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='Professor.Professor')),
            ],
        ),
    ]
