# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
