# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_auto_20180129_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('survey', 'order'), 'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
    ]
