# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='professors', to='Course.Course'),
        ),
    ]
