# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(max_length=4)),
                ('end_year', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='educationalyear',
            unique_together=set([('start_year', 'end_year')]),
        ),
    ]
