# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0002_auto_20180127_2215'),
        ('Student', '0001_initial'),
        ('Response', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('survey', 'student')]),
        ),
    ]
