# Generated by Django 2.0.1 on 2018-01-24 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('id_number', models.CharField(max_length=30, unique=True, verbose_name='ID number')),
                ('name', models.CharField(max_length=300)),
                ('mobile_number', models.CharField(max_length=15)),
                ('secondary_email', models.EmailField(max_length=100)),
                ('type', models.CharField(choices=[('fr', 'Fresh'), ('ot', 'Other')], default='fr', max_length=2)),
            ],
        ),
    ]
