# Generated by Django 2.0.1 on 2018-01-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
