# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 17:58
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20180122_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=models.CharField(max_length=50, unique=True), max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default=builtins.id(1), max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
